name: insidex_app
description: "InsideX - Sound Healing & Subliminal App"
publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Responsive
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  auto_size_text: ^3.0.0
  lottie: ^3.1.0

  firebase_analytics: ^11.0.1
  firebase_crashlytics: ^4.1.3
  marquee: ^2.2.3
  flutter_secure_storage: ^9.0.0
  device_preview: ^1.3.1
  package_info_plus: ^8.0.0

  # State Management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Revenuecat
  purchases_flutter: ^9.8.0

  # Localization
  intl: ^0.20.2
  flutter_markdown: ^0.6.23
  url_launcher: ^6.3.1
  country_flags: ^3.0.0

  # Download
  encrypt: ^5.0.3
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.0

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase - Compatible versions
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  cloud_functions: ^5.0.3
  firebase_app_check: ^0.3.2+10

  # Notification packages
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.0
  flutter_timezone: ^3.0.1
  background_fetch: ^1.3.2

  # Audio packages
  just_audio: ^0.10.4
  audio_service: ^0.18.18
  audio_video_progress_bar: ^2.0.3
  audio_session: ^0.1.21
  crypto: ^3.0.3
  rxdart: ^0.27.7
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  file_picker: ^10.3.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/legal/en/
    - assets/legal/ru/
    - assets/legal/tr/
    - assets/legal/hi/
    - assets/animations/categories/
    - assets/animations/ui/
    - assets/animations/avatars/
    - assets/content/en/
    - assets/content/tr/
    - assets/content/ru/
    - assets/content/hi/
  #flutter_icons:
  #android: true
  #ios: true
  #image_path: "assets/icons/app_icon.png"
  #adaptive_icon_background: "#FFFFFF"
  #adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  generate: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_icon.png

  color_dark: "#121212"
  image_dark: assets/images/splash_icon.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_icon.png
    color_dark: "#121212"
    image_dark: assets/images/splash_icon.png

  ios: true
  web: false
